/**
 * Indonesian Administrative Divisions Data
 * This file contains the hierarchical data for Provinces, Cities/Regencies, Districts, and Villages.
 *
 * Note: Truly exhaustive data (83,000+ villages) is typically handled via dynamic APIs.
 * This file provides a comprehensive set of major regions and a structure for easy expansion.
 */

export const provinces: string[] = [
  "ACEH",
  "SUMATERA UTARA",
  "SUMATERA BARAT",
  "RIAU",
  "KEPULAUAN RIAU",
  "JAMBI",
  "BENGKULU",
  "SUMATERA SELATAN",
  "KEPULAUAN BANGKA BELITUNG",
  "LAMPUNG",
  "DKI JAKARTA",
  "JAWA BARAT",
  "BANTEN",
  "JAWA TENGAH",
  "DI YOGYAKARTA",
  "JAWA TIMUR",
  "BALI",
  "NUSA TENGGARA BARAT",
  "NUSA TENGGARA TIMUR",
  "KALIMANTAN BARAT",
  "KALIMANTAN TENGAH",
  "KALIMANTAN SELATAN",
  "KALIMANTAN TIMUR",
  "KALIMANTAN UTARA",
  "SULAWESI UTARA",
  "GORONTALO",
  "SULAWESI TENGAH",
  "SULAWESI BARAT",
  "SULAWESI SELATAN",
  "SULAWESI TENGGARA",
  "MALUKU",
  "MALUKU UTARA",
  "PAPUA",
  "PAPUA BARAT",
  "PAPUA TENGAH",
  "PAPUA PEGUNUNGAN",
  "PAPUA SELATAN",
  "PAPUA BARAT DAYA",
];

export const provinceCities: Record<string, string[]> = {
  ACEH: [
    "BANDA ACEH",
    "SABANG",
    "LHOKSEUMAWE",
    "LANGSA",
    "SUBULUSSALAM",
    "ACEH BESAR",
    "ACEH UTARA",
    "ACEH TIMUR",
    "ACEH TENGAH",
    "ACEH BARAT",
    "ACEH SELATAN",
    "ACEH TENGGARA",
    "ACEH SINGKIL",
    "ACEH JAYA",
    "ACEH BARAT DAYA",
    "ACEH TAMIANG",
    "NAGAN RAYA",
    "BENER MERIAH",
    "PIDIE",
    "PIDIE JAYA",
    "BIREUEN",
    "SIMEULUE",
    "GAYO LUES",
  ],
  "SUMATERA UTARA": [
    "MEDAN",
    "BINJAI",
    "PEMATANGSIANTAR",
    "TEBING TINGGI",
    "TANJUNG BALAI",
    "SIBOLGA",
    "PADANG SIDEMPUAN",
    "GUNUNGSITOLI",
    "DELI SERDANG",
    "LANGKAT",
    "KARO",
    "SIMALUNGUN",
    "ASAHAN",
    "LABUHANBATU",
    "TAPANULI UTARA",
    "TAPANULI SELATAN",
    "TAPANULI TENGAH",
    "DAIRI",
    "TOBA",
    "MANDAILING NATAL",
    "NIAS",
    "SERDANG BEDAGAI",
    "BATU BARA",
    "PADANG LAWAS",
    "PADANG LAWAS UTARA",
    "LABUHANBATU SELATAN",
    "LABUHANBATU UTARA",
    "NIAS UTARA",
    "NIAS BARAT",
    "NIAS SELATAN",
    "PAKPAK BHARAT",
    "HUMBANG HASUNDUTAN",
    "SAMOSIR",
  ],
  "SUMATERA BARAT": [
    "PADANG",
    "BUKITTINGGI",
    "PARIAMAN",
    "PADANG PANJANG",
    "SOLOK",
    "SAWAHLUNTO",
    "PAYAKUMBUH",
    "AGAM",
    "SOLOK",
    "SOLOK SELATAN",
    "PESISIR SELATAN",
    "TANAH DATAR",
    "PADANG PARIAMAN",
    "PASAMAN",
    "PASAMAN BARAT",
    "LIMA PULUH KOTA",
    "SIJUNJUNG",
    "DHARMASRAYA",
    "KEPULAUAN MENTAWAI",
  ],
  RIAU: [
    "PEKANBARU",
    "DUMAI",
    "KAMPAR",
    "INDRAGIRI HULU",
    "INDRAGIRI HILIR",
    "BENGKALIS",
    "SIAK",
    "PELALAWAN",
    "ROKAN HULU",
    "ROKAN HILIR",
    "KUANTAN SINGINGI",
    "KEPULAUAN MERANTI",
  ],
  "KEPULAUAN RIAU": [
    "BATAM",
    "TANJUNGPINANG",
    "BINTAN",
    "KARIMUN",
    "NATUNA",
    "LINGGA",
    "KEPULAUAN ANAMBAS",
  ],
  JAMBI: [
    "JAMBI",
    "SUNGAI PENUH",
    "BATANGHARI",
    "BUNGO",
    "KERINCI",
    "MERANGIN",
    "MUARO JAMBI",
    "SAROLANGUN",
    "TANJUNG JABUNG TIMUR",
    "TANJUNG JABUNG BARAT",
    "TEBO",
  ],
  BENGKULU: [
    "BENGKULU",
    "BENGKULU SELATAN",
    "BENGKULU TENGAH",
    "BENGKULU UTARA",
    "KAUR",
    "KEPAHIANG",
    "LEBONG",
    "MUKOMUKO",
    "REJANG LEBONG",
    "SELUMA",
  ],
  "SUMATERA SELATAN": [
    "PALEMBANG",
    "LUBUKLINGGAU",
    "PAGAR ALAM",
    "PRABUMULIH",
    "BANYUASIN",
    "EMPAT LAWANG",
    "LAHAT",
    "MUARA ENIM",
    "MUSI BANYUASIN",
    "MUSI RAWAS",
    "OGAN ILIR",
    "OGAN KOMERING ILIR",
    "OGAN KOMERING ULU",
    "OGAN KOMERING ULU SELATAN",
    "OGAN KOMERING ULU TIMUR",
    "PENUKAL ABAB LEMATANG ILIR",
    "MUSI RAWAS UTARA",
  ],
  "KEPULAUAN BANGKA BELITUNG": [
    "PANGKALPINANG",
    "BANGKA",
    "BANGKA BARAT",
    "BANGKA SELATAN",
    "BANGKA TENGAH",
    "BELITUNG",
    "BELITUNG TIMUR",
  ],
  LAMPUNG: [
    "BANDAR LAMPUNG",
    "METRO",
    "LAMPUNG BARAT",
    "LAMPUNG SELATAN",
    "LAMPUNG TENGAH",
    "LAMPUNG TIMUR",
    "LAMPUNG UTARA",
    "MESUJI",
    "PESAWARAN",
    "PESISIR BARAT",
    "PRINGSEWU",
    "TANGGAMUS",
    "TULANG BAWANG",
    "TULANG BAWANG BARAT",
    "WAY KANAN",
  ],
  "DKI JAKARTA": [
    "JAKARTA SELATAN",
    "JAKARTA TIMUR",
    "JAKARTA PUSAT",
    "JAKARTA BARAT",
    "JAKARTA UTARA",
    "KEPULAUAN SERIBU",
  ],
  "JAWA BARAT": [
    "BANDUNG",
    "BEKASI",
    "DEPOK",
    "BOGOR",
    "CIMAHI",
    "TASIKMALAYA",
    "CIREBON",
    "BANJAR",
    "SUKABUMI",
    "BANDUNG BARAT",
    "CIANJUR",
    "GARUT",
    "INDRAMAYU",
    "KARAWANG",
    "KUNINGAN",
    "MAJALENGKA",
    "PANGANDARAN",
    "PURWAKARTA",
    "SUBANG",
    "SUKABUMI",
    "SUMEDANG",
    "CIAMIS",
  ],
  BANTEN: [
    "TANGERANG",
    "TANGERANG SELATAN",
    "SERANG",
    "CILEGON",
    "LEBAK",
    "PANDEGLANG",
  ],
  "JAWA TENGAH": [
    "SEMARANG",
    "SURAKARTA",
    "MAGELANG",
    "PEKALONGAN",
    "SALATIGA",
    "TEGAL",
    "BANJARNEGARA",
    "BANYUMAS",
    "BATANG",
    "BLORA",
    "BOYOLALI",
    "BREBES",
    "CILACAP",
    "DEMAK",
    "GROBOGAN",
    "JEPARA",
    "KARANGANYAR",
    "KEBUMEN",
    "KENDAL",
    "KLATEN",
    "KUDUS",
    "PATI",
    "PEMALANG",
    "PURBALINGGA",
    "PURWOREJO",
    "REMBANG",
    "SRAGEN",
    "SUKOHARJO",
    "TEMANGGUNG",
    "WONOGIRI",
    "WONOSOBO",
  ],
  "DI YOGYAKARTA": [
    "YOGYAKARTA",
    "SLEMAN",
    "BANTUL",
    "KULON PROGO",
    "GUNUNGKIDUL",
  ],
  "JAWA TIMUR": [
    "SURABAYA",
    "MALANG",
    "KEDIRI",
    "BLITAR",
    "MADIUN",
    "PASURUAN",
    "PROBOLINGGO",
    "BATU",
    "MOJOKERTO",
    "SIDOARJO",
    "GRESIK",
    "BANYUWANGI",
    "BOJONEGORO",
    "BONDOWOSO",
    "JEMBER",
    "JOMBANG",
    "LAMONGAN",
    "LUMAJANG",
    "MAGETAN",
    "NGANJUK",
    "NGAWI",
    "PACITAN",
    "PAMEKASAN",
    "PONOROGO",
    "SAMPANG",
    "SITUBONDO",
    "SUMENEP",
    "TRENGGALEK",
    "TUBAN",
    "TULUNGAGUNG",
  ],
  BALI: [
    "DENPASAR",
    "BADUNG",
    "GIANYAR",
    "TABANAN",
    "BULELENG",
    "KARANGASEM",
    "KLUNGKUNG",
    "BANGLI",
    "JEMBRANA",
  ],
  "NUSA TENGGARA BARAT": [
    "MATARAM",
    "BIMA",
    "LOMBOK BARAT",
    "LOMBOK TENGAH",
    "LOMBOK TIMUR",
    "LOMBOK UTARA",
    "SUMBAWA",
    "SUMBAWA BARAT",
    "DOMPU",
  ],
  "NUSA TENGGARA TIMUR": [
    "KUPANG",
    "ALOR",
    "BELU",
    "ENDE",
    "FLORES TIMUR",
    "KUPANG",
    "LEMBATA",
    "MALAKA",
    "MANGGARAI",
    "MANGGARAI BARAT",
    "MANGGARAI TIMUR",
    "NGADA",
    "NAGEKEO",
    "ROTE NDAO",
    "SABU RAIJUA",
    "SIKKA",
    "SUMBA BARAT",
    "SUMBA BARAT DAYA",
    "SUMBA TENGAH",
    "SUMBA TIMUR",
    "TIMOR TENGAH SELATAN",
    "TIMOR TENGAH UTARA",
  ],
  "KALIMANTAN BARAT": [
    "PONTIANAK",
    "SINGKAWANG",
    "BENGKAYANG",
    "KAPUAS HULU",
    "KAYONG UTARA",
    "KETAPANG",
    "KUBU RAYA",
    "LANDAK",
    "MELAWI",
    "MEMPAWAH",
    "SAMBAS",
    "SANGGAU",
    "SEKADAU",
    "SINTANG",
  ],
  "KALIMANTAN TENGAH": [
    "PALANGKA RAYA",
    "BARITO SELATAN",
    "BARITO TIMUR",
    "BARITO UTARA",
    "GUNUNG MAS",
    "KAPUAS",
    "KATINGAN",
    "KOTAWARINGIN BARAT",
    "KOTAWARINGIN TIMUR",
    "LAMANDAU",
    "MURUNG RAYA",
    "PULANG PISAU",
    "SUKAMARA",
    "SERUYAN",
  ],
  "KALIMANTAN SELATAN": [
    "BANJARMASIN",
    "BANJARBARU",
    "BALANGAN",
    "BANJAR",
    "BARITO KUALA",
    "HULU SUNGAI SELATAN",
    "HULU SUNGAI TENGAH",
    "HULU SUNGAI UTARA",
    "KOTABARU",
    "TABALONG",
    "TANAH BUMBU",
    "TANAH LAUT",
    "TAPIN",
  ],
  "KALIMANTAN TIMUR": [
    "SAMARINDA",
    "BALIKPAPAN",
    "BONTANG",
    "BERAU",
    "KUTAI BARAT",
    "KUTAI KARTANEGARA",
    "KUTAI TIMUR",
    "MAHAKAM ULU",
    "PASER",
    "PENAJAM PASER UTARA",
  ],
  "KALIMANTAN UTARA": [
    "TARAKAN",
    "BULUNGAN",
    "MALINAU",
    "NUNUKAN",
    "TANA TIDUNG",
  ],
  "SULAWESI UTARA": [
    "MANADO",
    "BITUNG",
    "TOMOHON",
    "KOTAMOBAGU",
    "BOLAANG MONGONDOW",
    "BOLAANG MONGONDOW SELATAN",
    "BOLAANG MONGONDOW TIMUR",
    "BOLAANG MONGONDOW UTARA",
    "KEPULAUAN SANGIHE",
    "KEPULAUAN SITARO",
    "KEPULAUAN TALAUD",
    "MINAHASA",
    "MINAHASA SELATAN",
    "MINAHASA TENGGARA",
    "MINAHASA UTARA",
  ],
  GORONTALO: [
    "GORONTALO",
    "BOALEMO",
    "BONE BOLANGO",
    "GORONTALO UTARA",
    "POHUWATO",
  ],
  "SULAWESI TENGAH": [
    "PALU",
    "BANGGAI",
    "BANGGAI KEPULAUAN",
    "BANGGAI LAUT",
    "BUOL",
    "DONGGALA",
    "MOROWALI",
    "MOROWALI UTARA",
    "PARIGI MOUTONG",
    "POSO",
    "SIGI",
    "TOJO UNA-UNA",
    "TOLI-TOLI",
  ],
  "SULAWESI BARAT": [
    "MAMUJU",
    "MAJENE",
    "MAMASA",
    "MAMUJU TENGAH",
    "MAMUJU UTARA",
    "POLEWALI MANDAR",
  ],
  "SULAWESI SELATAN": [
    "MAKASSAR",
    "PAREPARE",
    "PALOPO",
    "BANTAENG",
    "BARRU",
    "BONE",
    "BULUKUMBA",
    "ENREKANG",
    "GOWA",
    "JENEPONTO",
    "KEPULAUAN SELAYAR",
    "LUWU",
    "LUWU TIMUR",
    "LUWU UTARA",
    "MAROS",
    "PANGKAJENE DAN KEPULAUAN",
    "PINRANG",
    "SIDENRENG RAPPANG",
    "SINJAI",
    "SOPPENG",
    "TAKALAR",
    "TANA TORAJA",
    "TORAJA UTARA",
    "WAJO",
  ],
  "SULAWESI TENGGARA": [
    "KENDARI",
    "BAUBAU",
    "BOMBANA",
    "BUTON",
    "BUTON SELATAN",
    "BUTON TENGAH",
    "BUTON UTARA",
    "KOLAKA",
    "KOLAKA TIMUR",
    "KOLAKA UTARA",
    "KONAWE",
    "KONAWE KEPULAUAN",
    "KONAWE SELATAN",
    "KONAWE UTARA",
    "MUNA",
    "MUNA BARAT",
    "WAKATOBI",
  ],
  MALUKU: [
    "AMBON",
    "TUAL",
    "BURU",
    "BURU SELATAN",
    "KEPULAUAN ARU",
    "KEPULAUAN TANIMBAR",
    "MALUKU BARAT DAYA",
    "MALUKU TENGAH",
    "MALUKU TENGGARA",
    "SERAM BAGIAN BARAT",
    "SERAM BAGIAN TIMUR",
  ],
  "MALUKU UTARA": [
    "TERNATE",
    "TIDORE KEPULAUAN",
    "HALMAHERA BARAT",
    "HALMAHERA TENGAH",
    "HALMAHERA UTARA",
    "HALMAHERA SELATAN",
    "KEPULAUAN SULA",
    "HALMAHERA TIMUR",
    "PULAU MOROTAI",
    "PULAU TALIABU",
  ],
  PAPUA: [
    "JAYAPURA",
    "BIAK NUMFOR",
    "KEPULAUAN YAPEN",
    "KEEROM",
    "MAMBERAMO RAYA",
    "SARMI",
    "SUPIORI",
    "WAROPEN",
  ],
  "PAPUA BARAT": [
    "MANOKWARI",
    "FAKFAK",
    "KAIMANA",
    "MANOKWARI SELATAN",
    "PEGUNUNGAN ARFAK",
    "TELUK BINTUNI",
    "TELUK WONDAMA",
  ],
  "PAPUA TENGAH": [
    "NABIRE",
    "DEIYAI",
    "DOGIYAI",
    "INTAN JAYA",
    "MIMIKA",
    "PANIAI",
    "PUNCAK",
    "PUNCAK JAYA",
  ],
  "PAPUA PEGUNUNGAN": [
    "JAYAWIJAYA",
    "JALUKIMO",
    "LANNY JAYA",
    "MAMBERAMO TENGAH",
    "NDUGA",
    "PEGUNUNGAN BINTANG",
    "TOLIKARA",
    "YAHUKIMO",
    "YALIMO",
  ],
  "PAPUA SELATAN": ["MERAUKE", "ASMAT", "BOVEN DIGOEL", "MAPPI"],
  "PAPUA BARAT DAYA": [
    "SORONG",
    "MAYBRAT",
    "RAJA AMPAT",
    "SORONG SELATAN",
    "TAMBRAUW",
  ],
};

/**
 * Detailed mapping of Cities -> Districts -> Villages
 */
export const indonesianLocations: Record<
  string,
  Record<string, Record<string, string[]>>
> = {
  ACEH: {
    "BANDA ACEH": {
      MEURAXA: [
        "LAMPULO",
        "Ulee Lheue",
        "Punge Ujong",
        "Blang Oi",
        "Deah Baro",
        "Deah Glumpang",
        "Lambung",
        "Pie",
        "Alue Deah Teungoh",
      ],
      "KUTA RAJA": ["KEUDE ACEH", "PEULANGGAHAN", "Lampaseh Kota", "Merduati"],
      "SYIAH KUALA": [
        "Kopelma Darussalam",
        "Jeulingke",
        "Tibang",
        "Alue Naga",
        "Ie Masen Kaye Adang",
      ],
      BAITURRAHMAN: [
        "Kampung Baru",
        "Neusu Jaya",
        "Neusu Aceh",
        "Peuniti",
        "Seutui",
        "Sukaramai",
      ],
      "LUENG BATA": [
        "Lueng Bata",
        "Batoh",
        "Cot Mesjid",
        "Lamdom",
        "Panteriek",
      ],
      "JAYA BARU": [
        "Bitai",
        "Empee Trieng",
        "Geuceu Meunara",
        "Lamjamee",
        "Lampoh Daya",
        "Ulee Pata",
      ],
      "BANDA RAYA": [
        "Geuceu Komplek",
        "Geuceu Kayee Jato",
        "Lhong Raya",
        "Lhong Cut",
        "Menerbo",
      ],
      "ULEE KARENG": [
        "Ulee Kareng",
        "Pango Raya",
        "Pango Deah",
        "Ie Masen Ulee Kareng",
        "Ceurih",
      ],
    },
    SABANG: {
      SUKAKARYA: ["ANEUK LAOT", "KRUENG RAYA", "Iboih", "Bapuri"],
      SUKAJAYA: ["BALOHAN", "COT BA'U", "Ie Meulee", "Jaboi"],
    },
    "ACEH BESAR": {
      "DARUL IMARAH": [
        "PUNIE",
        "LHOONG RAYA",
        "Garot",
        "Gue Gajah",
        "Lampeuneurut Ujong Blang",
        "Lampiek",
        "Lamreung",
      ],
      "INGIN JAYA": [
        "Lambaro",
        "Lubok Sukon",
        "Pagar Air",
        "Siron",
        "Meunasah Manyang",
      ],
      "PEUKAN BADA": ["Lamguron", "Lampageu", "Lamteh", "Pulo Sarok"],
    },
  },
  "SUMATERA UTARA": {
    MEDAN: {
      "MEDAN BARU": [
        "DARAT",
        "MERDEKA",
        "BABURA",
        "PETISAH HULU",
        "PETISAH TENGAH",
        "PADANG BULAN",
      ],
      "MEDAN AREA": ["PASAR MERAH", "SEI RENGAS", "SUKAMAJU", "TEGAL SARI"],
      "MEDAN KOTA": [
        "PASAR BARU",
        "PANDAU HULU I",
        "SUDIREJO",
        "TELADAN BARAT",
      ],
      "MEDAN HELVETIA": [
        "CINTA DAMAI",
        "DWI KORA",
        "HELVETIA",
        "TANJUNG GUSTA",
      ],
      "MEDAN DENAI": ["BINJAI", "DENAI", "MENTENG", "TEGAL SARI MANDALA"],
      "MEDAN JOHOR": [
        "GEDUNG JOHOR",
        "KWALU BEKALA",
        "PANGKALAN MASYHUR",
        "TITIK KUNING",
      ],
      "MEDAN AMPLAS": ["AMPLAS", "BANGUN MULIA", "SITIREJO", "TIMBANG DELI"],
      "MEDAN BELAWAN": ["BELAWAN I", "BELAWAN II", "BELAWAN BAHARI", "BELAWAN BAHAGIA", "BELAWAN SI CANANG"],
      "MEDAN DELI": ["MABAR", "MABAR HILIR", "KOTA BANGUN", "TANJUNG MULIA"],
      "MEDAN LABUHAN": ["MARTUBUNG", "PEKAN LABUHAN", "SEI MATI", "TANGKAHAN"],
      "MEDAN MARELAN": ["LABUHAN DELI", "PAYA PASIR", "RENGAS PULAU", "TERJUN"],
      "MEDAN PERJUANGAN": ["SEI KERA", "SIDORAME", "TEGAL REJO"],
      "MEDAN PETISAH": ["PETISAH TENGAH", "SEI PUTIH", "SI_CANANG"],
      "MEDAN POLONIA": ["ANGGRUNG", "MADRAS HULU", "POLONIA", "SARI REJO"],
      "MEDAN SELAYANG": ["ASAM KUMBANG", "BERINGIN", "PADANG BULAN SELAYANG", "TANJUNG SARI"],
      "MEDAN SUNGGAL": ["BABURA SUNGGAL", "LALANG", "SEI SIKAMBING B", "SUNGGAL"],
      "MEDAN TEMBUNG": ["BANTAN", "INDRA KASIH", "SIDOREJO", "TEMBUNG"],
      "MEDAN TIMUR": ["DURIAN", "GLUGUR DARAT", "PULO BRAYAN"],
      "MEDAN TUNTUNGAN": ["LADANG BAMBU", "MANGGA", "SIMPANG SELAYANG", "TANJUNG SELAMAT"],
    },
    BINJAI: {
      "BINJAI KOTA": ["BINJAI", "KARTINI", "PEKAN BINJAI", "SATRIA"],
      "BINJAI BARAT": ["LIMAU SUNDAI", "PAYAROBA", "SUKAMAJU"],
    },
    PEMATANGSIANTAR: {
      "SIANTAR BARAT": ["PROKLAMASI", "SIMARITO", "DWIKORA", "BANJAR"],
      "SIANTAR TIMUR": ["ASUHAN", "KEPALA KOTA", "PARE"],
    },
  },
  "SUMATERA BARAT": {
    PADANG: {
      "PADANG BARAT": [
        "BELAKANG TANGSI",
        "PURUS",
        "KAMPUNG JAO",
        "RIMBO KALUANG",
        "UJUNG GURUN",
      ],
      "PADANG UTARA": [
        "AIR TAWAR BARAT",
        "AIR TAWAR TIMUR",
        "LOLONG BELANTI",
        "ULAK KARANG SELATAN",
      ],
      "KOTO TANGAH": [
        "AIR PACAH",
        "BALAI GADANG",
        "BATIPUH PANJANG",
        "LUBUK BUAYA",
        "PASIE NAN TIGO",
      ],
      "LUBUK BEGALUNG": [
        "BANUARAN NAN XX",
        "BATUANG TABA NAN XX",
        "GURUN LAWEH NAN XX",
        "PAMPANGAN NAN XX",
      ],
    },
    BUKITTINGGI: {
      "GUGUK PANJANG": ["BENTENG PASAR ATAS", "KAMPUNG CINA", "PULAI ANAK AIR"],
      MANDIANGIN: ["CAMPAGO IPUH", "PULAI ANAK AIR"],
    },
  },
  RIAU: {
    PEKANBARU: {
      TAMPAN: ["DELIMA", "SIDOMULYO BARAT", "TUAH KARYA", "SIMPANG BARU"],
      "BUKIT RAYA": ["SIMPANG TIGA", "TANGKERANG LABUAI", "TANGKERANG SELATAN"],
      "MARPOYAN DAMAI": [
        "MAHARATU",
        "SIDOMULYO TIMUR",
        "TANGKERANG BARAT",
        "TANGKERANG TENGAH",
      ],
    },
    DUMAI: { "DUMAI KOTA": ["LAKSAMANA", "RIMBA SEKAMPUNG", "SUKAJADI"] },
  },
  "KEPULAUAN RIAU": {
    BATAM: {
      "BATAM KOTA": [
        "BELIAN",
        "TELUK TERING",
        "BALOI PERMAI",
        "SUKAJADI",
        "SUNGAI PANAS",
      ],
      "LUBUK BAJA": ["PELITA", "BATU SELICIN", "BALOI INDAH", "KAMPUNG PELITA"],
      NONGSA: ["BATU BESAR", "KABILA", "SAMBAU", "TAMBELAN", "KAMPUNG SERAYA"],
    },
    TANJUNGPINANG: {
      "TANJUNGPINANG KOTA": ["PENYENGAT", "KAMPUNG BUGIS", "SENGGARANG"],
    },
  },
  JAMBI: {
    JAMBI: {
      TELANAIPURA: ["SIMPANG EMPAT", "TELANAI PURA", "BULURAN KENALI"],
      "KOTA BARU": ["KENALI ASAM BAWAH", "KENALI ASAM ATAS", "SUKA KARYA"],
    },
  },
  BENGKULU: {
    BENGKULU: {
      "RATU AGUNG": ["LEMPUING", "KEBUN KENANGA", "SAWAH LEBAR", "TANAH PATAH"],
    },
  },
  "SUMATERA SELATAN": {
    PALEMBANG: {
      "ILIR TIMUR I": ["20 ILIR", "SUNGAI PANGERAN", "18 ILIR"],
      SUKARAMI: [
        "TALANG BURUK",
        "KEBUN BUNGA",
        "TALANG BETUTU",
        "ALANG-ALANG LEBAR",
      ],
      "SEBERANG ULU I": ["15 ULU", "3-4 ULU", "8 ULU"],
      SAYO: ["SAYO", "BUKIT SANGKAL"],
      "ALANG-ALANG LEBAR": ["ALANG-ALANG LEBAR", "KARYA BARU", "TALANG KELAPA"],
      "BUKIT KECIL": ["19 ILIR", "22 ILIR", "24 ILIR", "26 ILIR", "TALANG SEMUT"],
      GANDUS: ["36 ILIR", "KARANG ANYAR", "KARANG JAYA", "PULO KERTO"],
      "ILIR BARAT I": ["26 ILIR D-I", "BUKIT LAMA", "BUKIT BARU", "LOROK PAKJO"],
      "ILIR BARAT II": ["27 ILIR", "28 ILIR", "29 ILIR", "30 ILIR", "35 ILIR"],
      "ILIR TIMUR II": ["1 ILIR", "2 ILIR", "3 ILIR", "5 ILIR", "7 ILIR", "LAWANG KIDUL"],
      "ILIR TIMUR III": ["8 ILIR", "DITO", "KUTO BATU"],
      JAKABARING: ["15 ULU", "8 ULU", "SILABERANTI"],
      KALIDONI: ["BUKIT SANGKAL", "KALIDONI", "SEI LAIS", "SEI SELAYUR"],
      KEMUNING: ["20 ILIR II", "ARIO KEMUNING", "PAHLAWAN", "PIPA REJA"],
      KERTAPATI: ["KARYA JAYA", "KERTAPATI", "OGAN BARU"],
      PLAJU: ["KOMPERTA", "PLAJU ILIR", "PLAJU ULU"],
      SAKO: ["SAKO", "SAKO BARU", "SIALANG"],
      "SEBERANG ULU II": ["11 ULU", "12 ULU", "13 ULU", "14 ULU", "SENTOSA"],
      "SEMATANG BORANG": ["KARYA MULYA", "SRIMULYA", "SUKAMULYA"],
    },
  },
  "KEPULAUAN BANGKA BELITUNG": {
    PANGKALPINANG: {
      TAMANSARI: ["BATIN TIKAL", "RAWAKALONG"],
      GERUNGGANG: ["AIR KEPALA TUJUH", "BUKIT MERAPIN"],
    },
  },
  LAMPUNG: {
    "BANDAR LAMPUNG": {
      "TANJUNG KARANG PUSAT": ["DURIAN PAYUNG", "GOTONG ROYONG", "PALAPA"],
      RAJABASA: ["RAJABASA", "RAJABASA JAYA", "RAJABASA RAYA"],
    },
    METRO: { "METRO PUSAT": ["IMOPURO", "METRO", "HADIMULYO"] },
  },
  "DKI JAKARTA": {
    "JAKARTA SELATAN": {
      "KEBAYORAN BARU": [
        "SELONG",
        "GUNUNG",
        "KRAMAT PELA",
        "GANDARIA UTARA",
        "CIPETE UTARA",
        "PULO",
        "MELAWAI",
        "PETOGOGAN",
        "RAWA BARAT",
        "SENAYAN",
      ],
      TEBET: [
        "TEBET BARAT",
        "TEBET TIMUR",
        "KEBON BARU",
        "MANGGARAI",
        "MANGGARAI SELATAN",
        "MENTENG DALAM",
        "BUKIT DURI",
      ],
      CILANDAK: [
        "CILANDAK BARAT",
        "CIPETE SELATAN",
        "GANDARIA SELATAN",
        "LEBAK BULUS",
        "PONDOK LABU",
      ],
      "PASAR MINGGU": [
        "PASAR MINGGU",
        "KEBAGUSAN",
        "JATI PADANG",
        "RAGUNAN",
        "PEJATEN BARAT",
        "PEJATEN TIMUR",
        "CILANDAK TIMUR",
      ],
      SETIABUDI: [
        "SETIABUDI",
        "KARET",
        "KARET KUNINGAN",
        "KARET SEMANGGI",
        "KUNINGAN TIMUR",
        "MENTENG ATAS",
        "PASAR MANGGIS",
        "GUNTUR",
      ],
      "KEBAYORAN LAMA": [
        "KEBAYORAN LAMA UTARA",
        "KEBAYORAN LAMA SELATAN",
        "PONDOK PINANG",
        "CIPULIR",
        "GROGOL UTARA",
        "GROGOL SELATAN",
      ],
      PESANGGRAHAN: [
        "PESANGGRAHAN",
        "BINTARO",
        "PETUKANGAN UTARA",
        "PETUKANGAN SELATAN",
        "ULUJAMI",
      ],
      "MAMPANG PRAPATAN": [
        "MAMPANG PRAPATAN",
        "BANGKA",
        "PELA MAMPANG",
        "TEGAL PARANG",
        "KUNINGAN BARAT",
      ],
      PANCORAN: [
        "PANCORAN",
        "KAYU MANIS",
        "BINONG",
        "DUREN TIGA",
        "KALIBATA",
        "RAWA JATI",
      ],
      JAGAKARSA: [
        "JAGAKARSA",
        "LENTENG AGUNG",
        "SRENGSENG SAWAH",
        "CIPEDAK",
        "TANJUNG BARAT",
        "CIGANJUR",
      ],
    },
    "JAKARTA TIMUR": {
      CAKUNG: [
        "CAKUNG BARAT",
        "CAKUNG TIMUR",
        "PULO GEBANG",
        "UJUNG MENTENG",
        "JATINEGARA",
        "PENGGILINGAN",
        "RAWA TERATE",
      ],
      "DUREN SAWIT": [
        "PONDOK KOPI",
        "PONDOK KELAPA",
        "DUREN SAWIT",
        "MALAKA JAYA",
        "MALAKA SARI",
        "PONDOK BAMBU",
        "KLENDER",
      ],
      "PULO GADUNG": [
        "PULO GADUNG",
        "RAWAMANGUN",
        "JATI",
        "KAYU PUTIH",
        "PISANGAN TIMUR",
        "CIPINANG",
        "KAMPUNG BARU",
      ],
      JATINEGARA: [
        "BALI MESTER",
        "KAMPUNG MELAYU",
        "BIDARA CINA",
        "CIPINANG CEMPEDAK",
        "CIPINANG MUARA",
        "CIPINANG BESAR UTARA",
        "CIPINANG BESAR SELATAN",
      ],
      "KRAMAT JATI": [
        "KRAMAT JATI",
        "BATU AMPAR",
        "BALEKAMBANG",
        "KAMPUNG TENGAH",
        "DUKUH",
        "PINANG RANTI",
        "MAKASAR",
      ],
      CIRACAS: [
        "CIRACAS",
        "CIBUBUR",
        "KELAPA DUA WETAN",
        "SUSUKAN",
        "RAMBUTAN",
      ],
      "PASAR REBO": ["BARU", "CIJANTUNG", "GEDONG", "KALISARI", "PEKAYON"],
      MATRAMAN: [
        "PISANGAN BARU",
        "UTAN KAYU SELATAN",
        "UTAN KAYU UTARA",
        "KAYU MANIS",
        "PAL MERIAM",
        "KEBON MANGGIS",
      ],
      CIPAYUNG: [
        "CIPAYUNG",
        "BAMBU APU",
        "CEGER",
        "LUBANG BUAYA",
        "MUNJUL",
        "PONDOK RANGGON",
        "SETU",
      ],
    },
    "JAKARTA PUSAT": {
      GAMBIR: [
        "GAMBIR",
        "CIDENG",
        "PETOJO UTARA",
        "PETOJO SELATAN",
        "KEBON KELAPA",
        "DURI PULO",
      ],
      "SAWAH BESAR": [
        "PASAR BARU",
        "MANGGA DUA SELATAN",
        "KARANG ANYAR",
        "KARTINI",
        "GUNUNG SAHARI UTARA",
      ],
      KEMAYORAN: [
        "KEMAYORAN",
        "GUNUNG SAHARI SELATAN",
        "KEBON KOSONG",
        "HARAPAN MULYA",
        "CERI",
        "UTAN PANJANG",
        "SUMUR BATU",
        "SERDANG",
      ],
      SENEN: ["SENEN", "KWITANG", "KENARI", "PASEBAN", "KRAMAT", "BUNGUR"],
      "CEMPAKA PUTIH": [
        "CEMPAKA PUTIH TIMUR",
        "CEMPAKA PUTIH BARAT",
        "RAWASARI",
      ],
      MENTENG: ["MENTENG", "PEGANGSAAN", "CIKINI", "KEBON SIRIH", "GONDANGDIA"],
      "TANAH ABANG": [
        "BENDUNGAN HILIR",
        "KARET TENGSIN",
        "KEBON MELATI",
        "KEBON KACANG",
        "KAMPUNG BALI",
        "PETAMBURAN",
        "GELORA",
      ],
      "JOHAR BARU": ["JOHAR BARU", "KAMPUNG RAWA", "GALUR", "TANAH TINGGI"],
    },
    "JAKARTA BARAT": {
      CENGKARENG: [
        "CENGKARENG BARAT",
        "CENGKARENG TIMUR",
        "DURI KOSAMBI",
        "KAPUK",
        "KEDAUNG KALI ANGKE",
        "RAWA BUAYA",
      ],
      "GROGOL PETAMBURAN": [
        "GROGOL",
        "JELAMBAR",
        "JELAMBAR BARU",
        "WIJAYA KUSUMA",
        "TANJUNG DUREN UTARA",
        "TANJUNG DUREN SELATAN",
        "TOMANG",
      ],
      KALIDERES: ["KALIDERES", "KAMAL", "PEGADUNGAN", "SEMANAN", "TEGAL ALUR"],
      "KEBON JERUK": [
        "KEBON JERUK",
        "KEDOYA UTARA",
        "KEDOYA SELATAN",
        "KELAPA DUA",
        "SUKABUMI UTARA",
        "SUKABUMI SELATAN",
        "DURI KEPA",
      ],
      KEMBANGAN: [
        "KEMBANGAN UTARA",
        "KEMBANGAN SELATAN",
        "MERUYA UTARA",
        "MERUYA SELATAN",
        "SRENGSENG",
        "JOGLO",
      ],
      PALMERAH: [
        "PALMERAH",
        "SLIPI",
        "KOTA BAMBU UTARA",
        "KOTA BAMBU SELATAN",
        "JATI PULO",
        "KEMANGGISAN",
      ],
      "TAMAN SARI": [
        "TAMAN SARI",
        "GLODOK",
        "KEAGUNGAN",
        "KRUKUT",
        "MAPHAR",
        "PINANGSIA",
        "TANGKI",
        "MANGGA BESAR",
      ],
      TAMBORA: [
        "TAMBORA",
        "ANGKE",
        "DURI SELATAN",
        "DURI UTARA",
        "JEMBATAN BESI",
        "JEMBATAN LIMA",
        "KALI ANYAR",
        "KRENDANG",
        "PEKOJAN",
        "ROA MALAKA",
        "TANAH SEREAL",
      ],
    },
    "JAKARTA UTARA": {
      CILINCING: [
        "CILINCING",
        "KALIBARU",
        "MARUNDA",
        "ROROTAN",
        "SUKAPURA",
        "SEMBERA",
        "TUGU PRATAMA",
      ],
      "KELAPA GADING": [
        "KELAPA GADING TIMUR",
        "KELAPA GADING BARAT",
        "PEGANGSAAN DUA",
      ],
      KOJA: [
        "KOJA",
        "LAGOA",
        "RAWA BADAK SELATAN",
        "RAWA BADAK UTARA",
        "TUGU SELATAN",
        "TUGU UTARA",
      ],
      PADEMANGAN: ["PADEMANGAN TIMUR", "PADEMANGAN BARAT", "ANCOL"],
      PENJARINGAN: [
        "PENJARINGAN",
        "PEJAGALAN",
        "PLUIT",
        "KAPUK MUARA",
        "KAMAL MUARA",
      ],
      "TANJUNG PRIOK": [
        "TANJUNG PRIOK",
        "KEBON BAWANG",
        "SUNGAI BAMBU",
        "PAPANGGO",
        "WARAKAS",
        "SUNTER AGUNG",
        "SUNTER JAYA",
      ],
    },
  },
  "JAWA BARAT": {
    BANDUNG: {
      COBLONG: [
        "DAGO",
        "CIPAGANTI",
        "LEBAKGEDE",
        "LEBAK SILIWANGI",
        "SADANG SERANG",
        "SEKELOA",
      ],
      LENGKONG: [
        "MALABAR",
        "BURANGRANG",
        "TURANGGA",
        "CIJAGRA",
        "CIKRIDIT",
        "LINGKAR SELATAN",
      ],
      CICENDO: [
        "ARJUNA",
        "HUSEIN SASTRANEGARA",
        "PAJAJARAN",
        "PASIR KALIKI",
        "SUKARAJA",
      ],
      "SUMUR BANDUNG": ["BRAGA", "KEBON PISANG", "BABAKAN CIAMIS", "MERDEKA"],
      ANDIR: [
        "CAMPAKA",
        "CIROYOM",
        "DUNGUS CARIANG",
        "GARUDA",
        "KEBON JERUK",
        "MALEBER",
      ],
      "ASTANA ANYAR": [
        "NYENGSERET",
        "PANJUNAN",
        "KARANGANYAR",
        "KARASAK",
        "PELINDUNG HEWAN",
      ],
      "BOJONGLOA KALER": [
        "BABAKAN",
        "BABAKAN TAROGONG",
        "JAMIKA",
        "KOP0",
        "SUKA ASIH",
      ],
      "CIBEUNYI KELER": ["CIHAPIT", "CITARUM", "TAMANSARI"],
      "ANTAPANI": ["ANTAPANI KIDUL", "ANTAPANI KULON", "ANTAPANI TENGAH"],
      "ARCAMANIK": ["CISARANTEN", "SUKAMISKIN"],
      "BABAKAN CIPARAY": ["BABAKAN", "BABAKAN CIPARAY", "SUKAHAI"],
      "BANDUNG KIDUL": ["BATUNUNGGAL", "KUJANGSARI", "WATES"],
      "BANDUNG KULON": ["CARINGIN", "CIBUNTU", "CIGONDEWAH"],
      "BATUNUNGGAL": ["BINONG", "GUMURUH", "KACAPIRING", "SAMOJA"],
      "BUAHBATU": ["CIJAWURA", "JATISARI", "MARGASARI"],
      "CIBEUNYING KIDUL": ["CICADAS", "SUKAMAJU", "SUKAPADA"],
      "CIBIRU": ["CIPADUNG", "PASIRBIRU"],
      "CIDADAP": ["HEGARMANAH", "PANDEWANGI", "LEDENG"],
      "CINAMBO": ["BABAKAN PENGHULU", "CISARANTEN WETAN"],
      "GEDEBAGE": ["CISARANTEN KIDUL", "RANCABOLANG"],
      "KIARACONDONG": ["BABAKAN SARI", "CICAHEUM", "SUKAPURA"],
      "MANDALAJATI": ["JATIHANDUAP", "KARANGPAMULAN", "PASIRIMPUN"],
      "PANYILEUKAN": ["CIPADUNG WETAN", "MEKARMULYA"],
      "RANCASARI": ["DERWATI", "MANJASARI", "MEKARJAYA"],
      "REGOL": ["BALONGGEDE", "CIATEUL", "PASIRLUYU"],
      "SUKAJADI": ["CIPEDES", "PASTEUR", "SUKAGALIH"],
      "SUKASARI": ["GEGERKALONG", "ISOLA", "SARIJADI"],
      "UJUNGBERUNG": ["CIGENDING", "PASANGGRAHAN", "PASIR_WANGI"],
    },
    BEKASI: {
      "BEKASI BARAT": [
        "BINTARA",
        "KRANJI",
        "KOTA BARU",
        "BINTARA JAYA",
        "JAKASAMPURNA",
      ],
      "BEKASI TIMUR": ["AREN JAYA", "BEKASI JAYA", "DUREN JAYA", "MARGAHAYU"],
      "BEKASI UTARA": [
        "HARAPAN BARU",
        "HARAPAN JAYA",
        "MARGA MULYA",
        "PERWIRA",
        "TELUK PUCUNG",
      ],
      "BEKASI SELATAN": [
        "JAKAMULYA",
        "JAKASETIA",
        "KAYURINGIN JAYA",
        "MARGA JAYA",
        "PEKAYON JAYA",
      ],
      RAWALUMBU: [
        "BOJONG MENTENG",
        "BOJONG RAWALUMBU",
        "PENGASINAN",
        "SEPANJANG JAYA",
      ],
      "BANTAR GEBANG": [
        "BANTAR GEBANG",
        "CIKETING UDIK",
        "CIKIWUL",
        "SUMUR BATU",
      ],
    },
    DEPOK: {
      BEJI: ["BEJI", "KEMIRI MUKA", "PONDOK CINA", "KUKUSAN", "BEJI TIMUR"],
      "PANCORAN MAS": [
        "DEPOK",
        "MAMPANG",
        "RANGKAPAN JAYA",
        "RANGKAPAN JAYA BARU",
        "DEPOK JAYA",
      ],
      CIMANGGIS: [
        "CURUG",
        "HARJAMUKTI",
        "MEKARSARI",
        "PASIR GUNUNG SELATAN",
        "TUGU",
      ],
      SUKMAJAYA: [
        "ABADIJAYA",
        "BAKTIJAYA",
        "CISALAK",
        "MEKAR JAYA",
        "SUKMAJAYA",
        "TIRTAJAYA",
      ],
      LIMO: ["GROGOL", "KRUKUT", "LIMO", "MERUYUNG"],
      CINERE: ["CINERE", "GANDUL", "PANGKALAN JATI", "PANGKALAN JATI BARU"],
      SAWANGAN: [
        "BEDAHAN",
        "CINANKA",
        "PASIR PUTIH",
        "SAWANGAN BARU",
        "SAWANGAN LAMA",
      ],
    },
    BOGOR: {
      "BOGOR TIMUR": [
        "BARANANGSIANG",
        "KATULAMPA",
        "SINDANGSARI",
        "SUKASARI",
        "TAJUR",
      ],
      "BOGOR TENGAH": [
        "BABAKAN",
        "BABAKAN PASAR",
        "CIBOGOR",
        "CIWULING",
        "GUDANG",
        "KEBON KELAPA",
        "PABATON",
        "PALEDANG",
        "PANARAGAN",
        "SEMPUR",
        "TEGAL LEGA",
      ],
      "BOGOR BARAT": [
        "BALUMBUNG JAYA",
        "BUBULAK",
        "CILUAR",
        "CURUG",
        "GUNUNG BATU",
        "LOJI",
        "MARGAYASA",
        "MENTENG",
        "PASIR JAYA",
        "PASIR KUDA",
        "PASIR MULYA",
        "SINDANGBARANG",
        "SITU GEDE",
      ],
      "BOGOR SELATAN": [
        "BATUTULIS",
        "BOJONGKERTA",
        "BONDONGAN",
        "CIKARET",
        "CIPAKU",
        "EMPANG",
        "GENTENG",
        "HARJASARI",
        "KERTAMAYA",
        "LAWANGGINTUNG",
        "MUARASARI",
        "MULYAHARJA",
        "PAKUAN",
        "RANCAMAYA",
        "RANGGAMEKAR",
      ],
      "BOGOR UTARA": [
        "BANTARJATI",
        "CIBULUH",
        "CILUAR",
        "CIMAHPAR",
        "CIPARIGI",
        "KEDUNG HALANG",
        "TANAH BARU",
        "TEGAL GUNDIL",
      ],
      "TANAH SAREAL": [
        "CIBADAK",
        "KAYUMANIS",
        "KEBON PEDES",
        "KEDUNG BADAK",
        "KEDUNG JAYA",
        "KEDUNG WARINGIN",
        "KENCANA",
        "MEKARWANGI",
        "SUKADAMAI",
        "SUKARESI",
        "TANAH SAREAL",
      ],
    },
  },
  BANTEN: {
    TANGERANG: {
      CIPONDOH: [
        "CIPONDOH",
        "PORIS PLAWAD",
        "PORIS PLAWAD INDAH",
        "PORIS PLAWAD UTARA",
        "KENANGA",
        "KETAPANG",
        "PETIR",
      ],
      KARAWACI: [
        "BOJONG JAYA",
        "BUGEL",
        "CIMONE",
        "CIMONE JAYA",
        "GERENDENG",
        "KARAWACI",
        "KARAWACI BARU",
        "KOANG JAYA",
        "MARGA SARI",
        "NUSA JAYA",
        "PABUARAN",
        "PABUARAN TUMPENG",
        "PASAR BARU",
        "SUKAJADI",
        "SUMUR PACING",
      ],
      CILEDUG: [
        "CILEDUG",
        "PANINGGILAN",
        "PANINGGILAN UTARA",
        "PARUNG SERAB",
        "SUDIMARA BARAT",
        "SUDIMARA JAYA",
        "SUDIMARA SELATAN",
        "SUDIMARA TIMUR",
      ],
      BATUCEPER: [
        "BATUCEPER",
        "BATUJAYA",
        "BATURENGAT",
        "KEBON BESAR",
        "PORIS GAGA",
        "PORIS GAGA BARU",
        "PORIS JAYA",
      ],
      BENDA: ["BELENDUNG", "BENDA", "JURUMUDI", "JURUMUDI BARU", "PAJANG"],
      CIBODAS: [
        "CIBODAS",
        "CIBODAS SARI",
        "CIBODAS BARU",
        "PANUNGGANGAN BARAT",
        "UWUNG JAYA",
      ],
      JATIUWUNG: [
        "ALAM JAYA",
        "GANDASARI",
        "JATAKE",
        "KADASARI",
        "MANIS JAYA",
        "PASIR JAYA",
      ],
      NEGLASARI: [
        "KARANG ANYAR",
        "KARANG SARI",
        "KEDAUNG BARU",
        "KEDAUNG WETAN",
        "MEKAR SARI",
        "NEGLASARI",
        "SELAPAJANG JAYA",
      ],
      PERIUK: [
        "GEBANG RAYA",
        "GEMBOR",
        "PERIUK",
        "PERIUK JAYA",
        "SANGIANG JAYA",
      ],
      PINANG: [
        "CIPETE",
        "KUNCIRAN",
        "KUNCIRAN INDAH",
        "KUNCIRAN JAYA",
        "NEROGTOG",
        "PACOJAN",
        "PANUNGGANGAN",
        "PANUNGGANGAN TIMUR",
        "PANUNGGANGAN UTARA",
        "PINANG",
        "SUDIMARA PINANG",
      ],
    },
    "TANGERANG SELATAN": {
      SERPONG: [
        "LENGKONG GUDANG",
        "LENGKONG GUDANG TIMUR",
        "LENGKONG WETAN",
        "RAWAMEKAR JAYA",
        "RAWABUNTU",
        "CIATER",
        "BUARAN",
        "SERPONG",
      ],
      "PONDOK AREN": [
        "JURANG MANGU BARAT",
        "JURANG MANGU TIMUR",
        "PONDOK AREN",
        "PONDOK KARYA",
        "PONDOK JAYA",
        "PONDOK BETUNG",
        "PONDOK PUCUNG",
        "PONDOK KACANG BARAT",
        "PONDOK KACANG TIMUR",
        "PERIGI LAMA",
        "PERIGI BARU",
      ],
      CIPUTAT: [
        "CIPUTAT",
        "CEMPAKA PUTIH",
        "SERUA",
        "SERUA INDAH",
        "JOMBANG",
        "SAWAH BARU",
        "SAWAH LAMA",
      ],
      "CIPUTAT TIMUR": [
        "CEMPAKA PUTIH",
        "PONDOK RANJI",
        "REMP0A",
        "RENGAS",
        "CIREUNDEU",
        "PISA_NGAN",
      ],
      PAMULANG: [
        "BAMBU APUS",
        "BENDA BARU",
        "KEDAUNG",
        "PAMULANG BARAT",
        "PAMULANG TIMUR",
        "PONDOK BENDA",
        "PONDOK CABE ILIR",
        "PONDOK CABE UDIK",
      ],
      "SERPONG UTARA": [
        "JELUPANG",
        "LENGKONG KARYA",
        "PAKU ALAM",
        "PAKU JAYA",
        "PAKULONAN",
        "PONDOK JAGUNG",
        "PONDOK JAGUNG TIMUR",
      ],
      SETU: [
        "BABAKAN",
        "BAKTI JAYA",
        "KADEMANGAN",
        "KERANGGAN",
        "MUNCUL",
        "SETU",
      ],
    },
  },
  "JAWA TENGAH": {
    SEMARANG: {
      "SEMARANG SELATAN": [
        "MUGASSARI",
        "PLEBURAN",
        "RANDUSARI",
        "BARUSARI",
        "LAMPER KIDUL",
        "LAMPER LOR",
        "LAMPER TENGAH",
        "PETERONGAN",
        "WONODRI",
        "BULUSTALAN",
      ],
      "SEMARANG BARAT": [
        "KEMBANGSARI",
        "PENDRIKAN KIDUL",
        "SEKAYU",
        "MIJEN",
        "MANYARAN",
        "KRAPYAK",
        "BOJONGSALAMAN",
        "CABEAN",
        "GISIKDRONO",
        "KALIBANTENG KIDUL",
        "KALIBANTENG KULON",
        "KARANGAYU",
        "KEMBANGSARI",
        "LEB0SARI",
        "NGEMPLAK SIMONGAN",
        "SALSARI",
        "TAWANGSARI",
        "TAWANGMAS",
      ],
      "SEMARANG TENGAH": [
        "BANGUNHARJO",
        "BRUMBUNGAN",
        "GABAHAN",
        "JAGALAN",
        "KARANGKIDUL",
        "KAUMAN",
        "KEMBANGSARI",
        "KRANGGAN",
        "MIROTO",
        "PANDANSARI",
        "PEKUNDEN",
        "PENDRIKAN KIDUL",
        "PENDRIKAN LOR",
        "PURWODINATAN",
        "SEKAYU",
      ],
      "SEMARANG TIMUR": [
        "BUGANGAN",
        "KARANGTEMPEL",
        "KARANGTURI",
        "KEMIJEN",
        "MLATIHARJO",
        "MLATIBARU",
        "REJOSARI",
        "SARIREJO",
        "REJOMULYO",
      ],
      "SEMARANG UTARA": [
        "BANDARHARJO",
        "BULU LOR",
        "DADAPSARI",
        "KUNINGAN",
        "PANGGUNG LOR",
        "PANGGUNG KIDUL",
        "PLOMBOKAN",
        "PURWOSARI",
        "TANJUNG MAS",
      ],
      BANYUMANIK: [
        "BANYUMANIK",
        "GEDAWANG",
        "JABUNGAN",
        "NGESREP",
        "PADANGSARI",
        "PEDALANGAN",
        "PUDAKPAYUNG",
        "SRONDOL KULON",
        "SRONDOL WETAN",
        "SUMURBOTO",
        "TINJOMOYO",
      ],
      GAJAHMUNGKUR: [
        "BENDAN DUWUR",
        "BENDAN NGAMPEL",
        "BENDUNGAN",
        "GAJAHMUNGKUR",
        "KARANGREJO",
        "LEMPONGSARI",
        "PETOMPON",
        "SAMPANGAN",
      ],
      GENUK: [
        "BANGETAYU KULON",
        "BANGETAYU WETAN",
        "GEBANGSARI",
        "GENUKSARI",
        "KARANGROTO",
        "KUDU",
        "MUKTIHARJO LOR",
        "PENGGARON LOR",
        "SEMBUNGHARJO",
        "TERBOYO KULON",
        "TERBOYO WETAN",
        "TRIMULYO",
      ],
      GUNUNGPATI: [
        "CEP0KO",
        "GUNUNGPATI",
        "JATIREJO",
        "KANDRI",
        "KALISIDI",
        "MANGUNSARI",
        "NGIJO",
        "NONGKOSAWIT",
        "PLALANGAN",
        "PONGANGAN",
        "PUDHAKPAYUNG",
        "SADENG",
        "SEKARAN",
        "SUKOREJO",
        "SUMUREJO",
      ],
      NGALIYAN: [
        "BAMBANKEREP",
        "BRINGIN",
        "GONDORIYO",
        "KALIPANCUR",
        "NGALIYAN",
        "PODOSARI",
        "PURWOYOSO",
        "TAMBAK AJI",
        "WONOSARI",
        "WATES",
      ],
    },
    SURAKARTA: {
      LAWEYAN: [
        "BUMI",
        "JAJAR",
        "KARANGASEM",
        "KERTEN",
        "LAWEYAN",
        "PAJANG",
        "PANULARAN",
        "PENUMPING",
        "PURWOSARI",
        "SONDOKAN",
        "SRIWEDARI",
      ],
      BANJARSARI: [
        "GILINGAN",
        "KADIPIRO",
        "NUSAkan",
        "BANJARSARI",
        "KEPORAN",
        "KESTALAN",
        "KETELAN",
        "MANAHAN",
        "MANGKUBUMEN",
        "PUNGGURAN",
        "SETABELAN",
        "SUMBER",
        "TIMURAN",
      ],
      JEBRES: [
        "GANDEKAN",
        "JAGALAN",
        "JEBRES",
        "KAMPUNG SEWU",
        "KEP0H",
        "MOJOSONGO",
        "PUCANG SAWIT",
        "PURWODININGRATAN",
        "SUDIROPRAJAN",
        "TEGALHARJO",
        "REJOSARI",
      ],
    },
  },
  "DI YOGYAKARTA": {
    YOGYAKARTA: {
      DANUREJAN: ["BAUSASRAN", "TEGAL PANGGUNG", "SURYATMAJAN"],
      GONDOMANAN: ["PRAWIRODIRJAN", "NGUPASAN"],
      GEDONGTENGEN: ["PRINGGOKUSUMAN", "SOSROMENDURAN"],
      JETIS: ["BUMIJO", "COKRODININGRATAN", "GOWONGAN"],
      KOTAGEDE: ["PRENGGAN", "PURBAYAN", "REJOWINANGUN"],
      KRATON: ["PANEMBAHAN", "KADIPATEN", "PATEHAN"],
      MANTRIJERON: ["SURYODININGRATAN", "GEDONGKIWO", "MANTRIJERON"],
      MERGANGSAN: ["BRONTOKUSUMAN", "KEPARAKAN", "WIROGUNAN"],
      NGAMPILAN: ["NGAMPILAN", "NOTOPRAJAN"],
      PAKUALAMAN: ["GUNUNGKETUR", "PURWOKINANTI"],
      TEGALREJO: ["TEGALREJO", "BENER", "KARANGWARU", "KRICAK"],
      UMBULHARJO: [
        "PANDEYAN",
        "SOROSUTAN",
        "GIWANGAN",
        "WARUNGBOTO",
        "MUJA MUJU",
        "SEMAKI",
        "TAHUNAN",
      ],
      WIROBRAJAN: ["WIROBRAJAN", "PATANGPULUHAN", "PAKUNCEN"],
    },
    SLEMAN: {
      DEPOK: ["CATURTUNGGAL", "MAGUWOHARJO", "CONDONGCATUR"],
      MLATI: ["SINDUADI", "SENDANGADI", "SUMBERADI", "TIRTOADI", "TLOGOADI"],
      GAMPING: [
        "AMBARKETAWANG",
        "BALECATUR",
        "BANYURADEN",
        "NOGOTIRTO",
        "TRIHANGGO",
      ],
      GODEAN: [
        "SIDOAGUNG",
        "SIDOKARTO",
        "SIDOLUHUR",
        "SIDOMULYO",
        "SIDOMOYO",
        "SIDOREJO",
        "SIDOARUM",
      ],
      KALASAN: ["PURWOMARTANI", "TIRTOMARTANI", "SELOMARTANI", "TAMANMARTANI"],
      NGAGLIK: [
        "DONOHARJO",
        "MINOMARTANI",
        "SARIHARJO",
        "SINDUHARJO",
        "SUKOHARJO",
        "SARDONOHARJO",
      ],
    },
  },
  "JAWA TIMUR": {
    SURABAYA: {
      GUBENG: ["AIRLANGGA", "BARATAJAYA", "MOJO", "PUCANG SEWU", "KERTAJAYA"],
      WONOKROMO: [
        "DARMO",
        "SAWAH PULO",
        "JAGIR",
        "NGAGEL",
        "NGAGELREJO",
        "WONOKROMO",
      ],
      TEGALSARI: [
        "KEDUNGDORO",
        "TEGALSARI",
        "WONOREJO",
        "DR. SUTOMO",
        "TEGALSARI",
      ],
      BUBUUTAN: [
        "ALUN-ALUN CONTONG",
        "BUBUTAN",
        "GUNDIH",
        "JEPARA",
        "TEMBOK DUKUH",
      ],
      GENTENG: [
        "EMBONG KALIASIN",
        "GENTENG",
        "KAPASARI",
        "KETABANG",
        "PENELEH",
      ],
      SIMOKERTO: [
        "KAPASAN",
        "SIDODADI",
        "SIMOKERTO",
        "SIMOLAWANG",
        "TAMBAKREJO",
      ],
      SAWAHAN: [
        "BANYU URIP",
        "KUPANG KRAJAN",
        "PAKIS",
        "PUTAT JAYA",
        "SAWAHAN",
        "PETEMON",
      ],
      TAMBAKSARI: [
        "DUKUH SETRO",
        "GADING",
        "KAPAS MADYA",
        "PACAR KEMBANG",
        "PACAR KELING",
        "PLOSO",
        "RANGKAH",
        "TAMBAKSARI",
      ],
      MULYOREJO: [
        "DUKUH SUTOREJO",
        "KALANGANYAR",
        "KALISARI",
        "MULYOREJO",
        "MANYAR SABRANGAN",
        "MOROKREMBANGAN",
      ],
    },
    MALANG: {
      KLOJEN: [
        "KLOJEN",
        "ORO-ORO DOWO",
        "PENANGGUNGAN",
        "RAMPAL CELAKET",
        "SAMAAN",
        "SIDODADI",
        "SUKOHARJO",
      ],
      LOWOKWARU: [
        "LOWOKWARU",
        "DINOYO",
        "MERJOSARI",
        "TULUNGREJO",
        "TUNGGULWULUNG",
        "TASIKMADU",
        "SUMBERSARI",
        "KETAWANGGEDE",
        "JATIMULYO",
      ],
      BLIMBING: [
        "ARJOSARI",
        "BALEARJOSARI",
        "BLIMBING",
        "BUNULREJO",
        "JODIPAN",
        "KESATRIAN",
        "PANDANWANGI",
        "POLEHAN",
        "PURWANTORO",
        "PURWODADI",
      ],
      SUKUN: [
        "BAKALANKRAJAN",
        "BANDULAN",
        "BANDUNGREJOSARI",
        "GADANG",
        "KARANGBESUKI",
        "KEBONSARI",
        "MULYOREJO",
        "PISANG CANDI",
        "SUKUN",
        "TANJUNREJO",
      ],
    },
  },
  BALI: {
    DENPASAR: {
      "DENPASAR BARAT": ["DAUH PURI", "PEMECUTAN", "TEGAL HARUM", "PADANG SAMBIAN"],
      "DENPASAR SELATAN": ["PANJER", "PEDUNGAN", "RENON", "SANUR", "SESETAN", "SIDAKARYA"],
      "DENPASAR TIMUR": ["KESIMAN", "PENATIH", "SUMERTA", "DANGIN PURI"],
      "DENPASAR UTARA": ["PEGUYANGAN", "UBUNG", "TONJA", "PEMECUTAN KAJA"],
    },
  },
  "SULAWESI SELATAN": {
    MAKASSAR: {
      BIRINGKANAYA: ["DAYA", "SUDIANG", "UNTIA", "PAC_C_E_RA_K_K_A_NG"],
      BONTOALA: ["BARAYA", "LA_YA_NG", "BONTOALA"],
      MAMAJANG: ["MAMAJANG", "PARANG", "SAMBUNG JAWA"],
      MANGGALA: ["ANTANG", "BANGKALA", "MANGGALA"],
      MARISO: ["MARISO", "PANAMBUNG", "MATTOANGING"],
      PANAKKUKANG: ["MASALE", "PANDANG", "PAROPO", "TODDOPULI"],
      RAPPOCINI: ["RAPPOCINI", "TIDUNG", "MAP_P_A_LA"],
      TALLO: ["TALLO", "KALUKU BODOA", "SUWANGGI"],
      TAMALANREA: ["TAMALANREA", "KAPASA", "BUNTUSU"],
      TAMALATE: ["BAROMBONG", "M_A_C_C_I_NI SOMBA", "PARANG TAMBUNG"],
      "UJUNG PANDANG": ["BARU", "BULOGADING", "MALOKU"],
      "UJUNG TANAH": ["CAMBAYA", "TABARANE"],
      WAJO: ["ENDE", "MALIMONGAN"],
    },
  },
};

export const getAllProvinces = () => provinces;
export const getCitiesByProvince = (province: string) =>
  provinceCities[province] || [];
export const getDistrictsByCity = (province: string, city: string) => {
  if (indonesianLocations[province] && indonesianLocations[province][city]) {
    return Object.keys(indonesianLocations[province][city]).map((d) =>
      d.toUpperCase(),
    );
  }
  return [];
};
export const getVillagesByDistrict = (
  province: string,
  city: string,
  district: string,
) => {
  if (
    indonesianLocations[province] &&
    indonesianLocations[province][city] &&
    indonesianLocations[province][city][district]
  ) {
    return indonesianLocations[province][city][district].map((v) =>
      v.toUpperCase(),
    );
  }
  return [];
};
