export const JUZ_OPTIONS = Array.from({ length: 30 }, (_, i) => i + 1);

export const SURAH_DATA = [
  { name: "Al-Fatihah", juz: [1], totalAyah: 7 },
  { name: "Al-Baqarah", juz: [1, 2, 3], totalAyah: 286 },
  { name: "Ali Imran", juz: [3, 4], totalAyah: 200 },
  { name: "An-Nisa'", juz: [4, 5, 6], totalAyah: 176 },
  { name: "Al-Ma'idah", juz: [6, 7], totalAyah: 120 },
  { name: "Al-An'am", juz: [7, 8], totalAyah: 165 },
  { name: "Al-A'raf", juz: [8, 9], totalAyah: 206 },
  { name: "Al-Anfal", juz: [9, 10], totalAyah: 75 },
  { name: "At-Taubah", juz: [10, 11], totalAyah: 129 },
  { name: "Yunus", juz: [11], totalAyah: 109 },
  { name: "Hud", juz: [11, 12], totalAyah: 123 },
  { name: "Yusuf", juz: [12, 13], totalAyah: 111 },
  { name: "Ar-Ra'd", juz: [13], totalAyah: 43 },
  { name: "Ibrahim", juz: [13], totalAyah: 52 },
  { name: "Al-Hijr", juz: [14], totalAyah: 99 },
  { name: "An-Nahl", juz: [14], totalAyah: 128 },
  { name: "Al-Isra'", juz: [15], totalAyah: 111 },
  { name: "Al-Kahf", juz: [15, 16], totalAyah: 110 },
  { name: "Maryam", juz: [16], totalAyah: 98 },
  { name: "Ta-Ha", juz: [16], totalAyah: 135 },
  { name: "Al-Anbiya'", juz: [17], totalAyah: 112 },
  { name: "Al-Hajj", juz: [17], totalAyah: 78 },
  { name: "Al-Mu'minun", juz: [18], totalAyah: 118 },
  { name: "An-Nur", juz: [18], totalAyah: 64 },
  { name: "Al-Furqan", juz: [18, 19], totalAyah: 77 },
  { name: "Asy-Syu'ara'", juz: [19], totalAyah: 227 },
  { name: "An-Naml", juz: [19, 20], totalAyah: 93 },
  { name: "Al-Qasas", juz: [20], totalAyah: 88 },
  { name: "Al-'Ankabut", juz: [20, 21], totalAyah: 69 },
  { name: "Ar-Rum", juz: [21], totalAyah: 60 },
  { name: "Luqman", juz: [21], totalAyah: 34 },
  { name: "As-Sajdah", juz: [21], totalAyah: 30 },
  { name: "Al-Ahzab", juz: [21, 22], totalAyah: 73 },
  { name: "Saba'", juz: [22], totalAyah: 54 },
  { name: "Fatir", juz: [22], totalAyah: 45 },
  { name: "Ya-Sin", juz: [22, 23], totalAyah: 83 },
  { name: "As-Saffat", juz: [23], totalAyah: 182 },
  { name: "Sad", juz: [23], totalAyah: 88 },
  { name: "Az-Zumar", juz: [23, 24], totalAyah: 75 },
  { name: "Ghafir", juz: [24], totalAyah: 85 },
  { name: "Fussilat", juz: [24, 25], totalAyah: 54 },
  { name: "Asy-Syura", juz: [25], totalAyah: 53 },
  { name: "Az-Zukhruf", juz: [25], totalAyah: 89 },
  { name: "Ad-Dukhan", juz: [25], totalAyah: 59 },
  { name: "Al-Jasiyah", juz: [25], totalAyah: 37 },
  { name: "Al-Ahqaf", juz: [26], totalAyah: 35 },
  { name: "Muhammad", juz: [26], totalAyah: 38 },
  { name: "Al-Fath", juz: [26], totalAyah: 29 },
  { name: "Al-Hujurat", juz: [26], totalAyah: 18 },
  { name: "Qaf", juz: [26], totalAyah: 45 },
  { name: "Az-Zariyat", juz: [26, 27], totalAyah: 60 },
  { name: "At-Tur", juz: [27], totalAyah: 49 },
  { name: "An-Najm", juz: [27], totalAyah: 62 },
  { name: "Al-Qamar", juz: [27], totalAyah: 55 },
  { name: "Ar-Rahman", juz: [27], totalAyah: 78 },
  { name: "Al-Waqi'ah", juz: [27], totalAyah: 96 },
  { name: "Al-Hadid", juz: [27], totalAyah: 29 },
  { name: "Al-Mujadilah", juz: [28], totalAyah: 22 },
  { name: "Al-Hasyr", juz: [28], totalAyah: 24 },
  { name: "Al-Mumtahanah", juz: [28], totalAyah: 13 },
  { name: "As-Saff", juz: [28], totalAyah: 14 },
  { name: "Al-Jumu'ah", juz: [28], totalAyah: 11 },
  { name: "Al-Munafiqun", juz: [28], totalAyah: 11 },
  { name: "At-Tagabun", juz: [28], totalAyah: 18 },
  { name: "At-Talaq", juz: [28], totalAyah: 12 },
  { name: "At-Tahrim", juz: [28], totalAyah: 12 },
  { name: "Al-Mulk", juz: [29], totalAyah: 30 },
  { name: "Al-Qalam", juz: [29], totalAyah: 52 },
  { name: "Al-Haqqah", juz: [29], totalAyah: 52 },
  { name: "Al-Ma'arij", juz: [29], totalAyah: 44 },
  { name: "Nuh", juz: [29], totalAyah: 28 },
  { name: "Al-Jinn", juz: [29], totalAyah: 28 },
  { name: "Al-Muzzammil", juz: [29], totalAyah: 20 },
  { name: "Al-Muddassir", juz: [29], totalAyah: 56 },
  { name: "Al-Qiyamah", juz: [29], totalAyah: 40 },
  { name: "Al-Insan", juz: [29], totalAyah: 31 },
  { name: "Al-Mursalat", juz: [29], totalAyah: 50 },
  { name: "An-Naba'", juz: [30], totalAyah: 40 },
  { name: "An-Nazi'at", juz: [30], totalAyah: 46 },
  { name: "'Abasa", juz: [30], totalAyah: 42 },
  { name: "At-Takwir", juz: [30], totalAyah: 29 },
  { name: "Al-Infitar", juz: [30], totalAyah: 19 },
  { name: "Al-Mutaffifin", juz: [30], totalAyah: 36 },
  { name: "Al-Insyiqaq", juz: [30], totalAyah: 25 },
  { name: "Al-Buruj", juz: [30], totalAyah: 22 },
  { name: "At-Tariq", juz: [30], totalAyah: 17 },
  { name: "Al-A'la", juz: [30], totalAyah: 19 },
  { name: "Al-Ghasyiyah", juz: [30], totalAyah: 26 },
  { name: "Al-Fajr", juz: [30], totalAyah: 30 },
  { name: "Al-Balad", juz: [30], totalAyah: 20 },
  { name: "Asy-Syams", juz: [30], totalAyah: 15 },
  { name: "Al-Lail", juz: [30], totalAyah: 21 },
  { name: "Ad-Duha", juz: [30], totalAyah: 11 },
  { name: "Asy-Syarh", juz: [30], totalAyah: 8 },
  { name: "At-Tin", juz: [30], totalAyah: 8 },
  { name: "Al-'Alaq", juz: [30], totalAyah: 19 },
  { name: "Al-Qadr", juz: [30], totalAyah: 5 },
  { name: "Al-Bayyinah", juz: [30], totalAyah: 8 },
  { name: "Az-Zalzalah", juz: [30], totalAyah: 8 },
  { name: "Al-'Adiyat", juz: [30], totalAyah: 11 },
  { name: "Al-Qari'ah", juz: [30], totalAyah: 11 },
  { name: "At-Takasur", juz: [30], totalAyah: 8 },
  { name: "Al-'Asr", juz: [30], totalAyah: 3 },
  { name: "Al-Humazah", juz: [30], totalAyah: 9 },
  { name: "Al-Fil", juz: [30], totalAyah: 5 },
  { name: "Quraisy", juz: [30], totalAyah: 4 },
  { name: "Al-Ma'un", juz: [30], totalAyah: 7 },
  { name: "Al-Kausar", juz: [30], totalAyah: 3 },
  { name: "Al-Kafirun", juz: [30], totalAyah: 6 },
  { name: "An-Nasr", juz: [30], totalAyah: 3 },
  { name: "Al-Lahab", juz: [30], totalAyah: 5 },
  { name: "Al-Ikhlas", juz: [30], totalAyah: 4 },
  { name: "Al-Falaq", juz: [30], totalAyah: 5 },
  { name: "An-Nas", juz: [30], totalAyah: 6 },
];
